### ISSUE TITLE
Typo report

### ISSUE THREAD

**Issue by JinchunChoi** [Beerkay/IoTResearch#2]
Dear Berkay,
Hello, I just found 1 typo in the list.

from
2018, **NDDS**, Decentralized Action Integrity for Trigger-Action IoT Platforms
to
2018, **NDSS**, Decentralized Action Integrity for Trigger-Action IoT Platforms

Thank you for listing up the IoT papers.

Sincerely,

**Comment by Beerkay** [comment]
Thanks,  fixed.
-Berkay
